# Notification content model labels
notifications_notificationsModel.description=Notification content model
notifications_notificationsModel.type.notifications_notification.title=Notification
notifications_notificationsModel.property.notifications_id.title=Notification ID
notifications_notificationsModel.property.notifications_userId.title=User ID
notifications_notificationsModel.property.notifications_message.title=Message
notifications_notificationsModel.property.notifications_timestamp.title=Timestamp
notifications_notificationsModel.property.notifications_isRead.title=Read
notifications_notificationsModel.property.notifications_type.title=Type
notifications_notificationsModel.property.notifications_url.title=URL
